

app.service('productService', [function(){
	// http://www.convertcsv.com/csv-to-json.htm
	// https://drive.google.com/file/d/0Bx_cJ8ynukC_SWpQZklvQ3FDMTQ/view?usp=sharing
	this.products = [
		{
			name: 'Samsung Galaxy Note 5 ',
			price: 724.89,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/81Xgvuv7ILL._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},
		{
			name: 'Apple MacBook Pro 15.4-Inch',
			price: 1929.00,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/816jzlNp%2B0L._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},
		{
			name: 'GoPro HERO4 BLACK 4K Action Camera',
			price: 499.99,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/41qIULouRhL._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},
		{
			name: 'Sandisk 200gb Micro SD',
			price: 13.54,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/81Z7-tiWzvL._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},
		{
			name: 'Apple MacBook Air',
			price: 894.99 ,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/51zsSjBYAzL._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},{
			name: 'PlayStation 4',
			price: 399.99 ,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/51ROi4d4puL._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},{
			name: 'Bose SoundLink Bluetooth Speaker III',
			price: 299.00 ,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/81UANmagJ8L._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},{
			name: 'LG Electronics G Watch R - Smart Watch',
			price: 289.99  ,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/412Sjb2vS2L._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},{
			name: 'Apple Magic Trackpad',
			price: 65.99,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/31G9orC5V8L._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},{
			name: 'NVIDIA SHIELD',
			price: 199.99,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/71on8Pa9fQL._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},{
			name: 'Bose QuietComfort 25',
			price: 299.00,
			rating: 5,
			img: 'http://ecx.images-amazon.com/images/I/51itR-iia7L._SL1500_.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		},{
			name: 'iPad Pro 12.9-inch',
			price: 799,
			rating: 5,
			img: 'http://b-i.forbesimg.com/patrickmoorhead/files/2013/11/iPad-Air.jpg',
			description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ac neque ac quam cursus auctor. Maecenas eget hendrerit dui. Integer ornare tellus non lobortis imperdiet. '
		}

	];
	this.movies = 

	[{"Title":"Blade Runner","Year":"1982","Rated":"R","Released":"25 Jun 1982","Runtime":"117 min","Genre":"Sci-Fi, Thriller","Director":"Ridley Scott","Writer":"Hampton Fancher (screenplay), David Webb Peoples (screenplay), Philip K. Dick (novel)","Actors":"Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos","Plot":"In a cyberpunk vision of the future, man has developed the technology to create replicants, human clones used to serve in the colonies outside Earth but with fixed lifespans. In Los Angeles, 2019, Deckard is a Blade Runner, a cop who specializes in terminating replicants. Originally in retirement, he is forced to re-enter the force when four replicants escape from an off-world colony to Earth.","Language":"English, German, Cantonese, Japanese, Hungarian","Country":"USA, Hong Kong, UK","Awards":"Nominated for 2 Oscars. Another 11 wins & 15 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTA4MDQxNTk2NDheQTJeQWpwZ15BbWU3MDE2NjIyODk@._V1_SX300.jpg","Metascore":"88","imdbRating":"8.2","imdbVotes":"419,589","imdbID":"tt0083658","Type":"movie","Response":"True"},
	{"Title":"The Wolf of Wall Street","Year":"2013","Rated":"R","Released":"25 Dec 2013","Runtime":"180 min","Genre":"Biography, Comedy, Crime","Director":"Martin Scorsese","Writer":"Terence Winter (screenplay), Jordan Belfort (book)","Actors":"Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey","Plot":"In The Wolf of Wall Street DiCaprio plays Belfort, a Long Island penny stockbroker who served 22 months in prison for defrauding investors in a massive 1990s securities scam that involved widespread corruption on Wall Street and in the corporate banking world, including shoe designer Steve Madden.","Language":"English, French","Country":"USA","Awards":"Nominated for 5 Oscars. Another 47 wins & 128 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.2","imdbVotes":"632,551","imdbID":"tt0993846","Type":"movie","Response":"True"},
	{"Title":"Warrior","Year":"2011","Rated":"PG-13","Released":"09 Sep 2011","Runtime":"140 min","Genre":"Drama, Sport","Director":"Gavin O'Connor","Writer":"Gavin O'Connor (screenplay), Anthony Tambakis (screenplay), Cliff Dorfman (screenplay), Gavin O'Connor (story), Cliff Dorfman (story)","Actors":"Joel Edgerton, Tom Hardy, Nick Nolte, Jennifer Morrison","Plot":"Two brothers face the fight of a lifetime - and the wreckage of their broken family - within the brutal, high-stakes world of Mixed Martial Arts (MMA) fighting in Lionsgate's action/drama, WARRIOR. An ex-Marine haunted by a tragic past, Tommy Riordan returns to his hometown of Pittsburgh and enlists his father, a recovered alcoholic and his former coach, to train him for an MMA tournament awarding the biggest purse in the history of the sport. As Tommy blazes a violent path towards the title prize, his brother, Brendan, a former MMA fighter unable to make ends meet as a public school teacher, returns to the amateur ring to provide for his family. Even though years have passed, recriminations and past betrayals keep Brendan bitterly estranged from both Tommy and his father. But when Brendan's unlikely rise as an underdog sets him on a collision course with Tommy, the two brothers must finally confront the forces that tore them apart, all the while waging the most intense, winner-takes-all battle of their lives.","Language":"English, Spanish","Country":"USA","Awards":"Nominated for 1 Oscar. Another 6 wins & 17 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk4ODk5MTMyNV5BMl5BanBnXkFtZTcwMDMyNTg0Ng@@._V1_SX300.jpg","Metascore":"71","imdbRating":"8.2","imdbVotes":"292,471","imdbID":"tt1291584","Type":"movie","Response":"True"},
	{"Title":"Gran Torino","Year":"2008","Rated":"R","Released":"09 Jan 2009","Runtime":"116 min","Genre":"Drama","Director":"Clint Eastwood","Writer":"Nick Schenk (screenplay), Dave Johannson (story), Nick Schenk (story)","Actors":"Clint Eastwood, Christopher Carley, Bee Vang, Ahney Her","Plot":"Walt Kowalski is a widower who holds onto his prejudices despite the changes in his Michigan neighborhood and the world around him. Kowalski is a grumpy, tough-minded, unhappy old man who can't get along with either his kids or his neighbors. He is a Korean War veteran whose prize possession is a 1972 Gran Torino he keeps in mint condition. When his neighbor Thao, a young Hmong teenager under pressure from his gang member cousin, tries to steal his Gran Torino, Kowalski sets out to reform the youth. Drawn against his will into the life of Thao's family, Kowalski is soon taking steps to protect them from the gangs that infest their neighborhood.","Language":"English, Hmong","Country":"USA, Germany","Awards":"Nominated for 1 Golden Globe. Another 22 wins & 10 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQyMTczMTAxMl5BMl5BanBnXkFtZTcwOTc1ODE0Mg@@._V1_SX300.jpg","Metascore":"72","imdbRating":"8.2","imdbVotes":"506,194","imdbID":"tt1205489","Type":"movie","Response":"True"},
	{"Title":"V for Vendetta","Year":"2005","Rated":"R","Released":"17 Mar 2006","Runtime":"132 min","Genre":"Action, Drama, Thriller","Director":"James McTeigue","Writer":"Andy Wachowski (screenplay), Lana Wachowski (screenplay), David Lloyd (graphic novel art)","Actors":"Natalie Portman, Hugo Weaving, Stephen Rea, Stephen Fry","Plot":"Tells the story of Evey Hammond and her unlikely but instrumental part in bringing down the fascist government that has taken control of a futuristic Great Britain. Saved from a life-and-death situation by a man in a Guy Fawkes mask who calls himself V, she learns a general summary of V's past and, after a time, decides to help him bring down those who committed the atrocities that led to Britain being in the shape that it is in.","Language":"English","Country":"USA, UK, Germany","Awards":"10 wins & 23 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_SX300.jpg","Metascore":"62","imdbRating":"8.2","imdbVotes":"709,179","imdbID":"tt0434409","Type":"movie","Response":"True"},
	{"Title":"A Beautiful Mind","Year":"2001","Rated":"PG-13","Released":"04 Jan 2002","Runtime":"135 min","Genre":"Biography, Drama","Director":"Ron Howard","Writer":"Akiva Goldsman, Sylvia Nasar (book)","Actors":"Russell Crowe, Ed Harris, Jennifer Connelly, Christopher Plummer","Plot":"From the heights of notoriety to the depths of depravity, John Forbes Nash, Jr. experienced it all. A mathematical genius, he made an astonishing discovery early in his career and stood on the brink of international acclaim. But the handsome and arrogant Nash soon found himself on a painful and harrowing journey of self-discovery. After many years of struggle, he eventually triumphed over his tragedy, and finally - late in life - received the Nobel Prize.","Language":"English","Country":"USA","Awards":"Won 4 Oscars. Another 32 wins & 58 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ4MDI2MzkwMl5BMl5BanBnXkFtZTYwMjk0NTA5._V1_SX300.jpg","Metascore":"72","imdbRating":"8.2","imdbVotes":"532,561","imdbID":"tt0268978","Type":"movie","Response":"True"},
	{"Title":"How to Train Your Dragon","Year":"2010","Rated":"PG","Released":"26 Mar 2010","Runtime":"98 min","Genre":"Animation, Adventure, Family","Director":"Dean DeBlois, Chris Sanders","Writer":"William Davies (screenplay), Dean DeBlois (screenplay), Chris Sanders (screenplay), Cressida Cowell (book)","Actors":"Jay Baruchel, Gerard Butler, Craig Ferguson, America Ferrera","Plot":"Long ago up North on the Island of Berk, the young Viking, Hiccup, wants to join his town's fight against the dragons that continually raid their town. However, his macho father and village leader, Stoik the Vast, will not allow his small, clumsy, but inventive son to do so. Regardless, Hiccup ventures out into battle and downs a mysterious Night Fury dragon with his invention, but can't bring himself to kill it. Instead, Hiccup and the dragon, whom he dubs Toothless, begin a friendship that would open up both their worlds as the observant boy learns that his people have misjudged the species. But even as the two each take flight in their own way, they find that they must fight the destructive ignorance plaguing their world.","Language":"English","Country":"USA","Awards":"Nominated for 2 Oscars. Another 30 wins & 51 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.2","imdbVotes":"421,636","imdbID":"tt0892769","Type":"movie","Response":"True"},
	{"Title":"Gone Girl","Year":"2014","Rated":"R","Released":"03 Oct 2014","Runtime":"149 min","Genre":"Drama, Mystery, Thriller","Director":"David Fincher","Writer":"Gillian Flynn (screenplay), Gillian Flynn (novel)","Actors":"Ben Affleck, Rosamund Pike, Neil Patrick Harris, Tyler Perry","Plot":"On the occasion of his fifth wedding anniversary, Nick Dunne reports that his wife, Amy, has gone missing. Under pressure from the police and a growing media frenzy, Nick's portrait of a blissful union begins to crumble. Soon his lies, deceits and strange behavior have everyone asking the same dark question: Did Nick Dunne kill his wife?","Language":"English","Country":"USA","Awards":"Nominated for 1 Oscar. Another 69 wins & 136 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_SX300.jpg","Metascore":"79","imdbRating":"8.2","imdbVotes":"456,460","imdbID":"tt2267998","Type":"movie","Response":"True"},
	{"Title":"The Sixth Sense","Year":"1999","Rated":"PG-13","Released":"06 Aug 1999","Runtime":"107 min","Genre":"Drama, Mystery, Thriller","Director":"M. Night Shyamalan","Writer":"M. Night Shyamalan","Actors":"Bruce Willis, Haley Joel Osment, Toni Collette, Olivia Williams","Plot":"Malcom Crowe is a child psychologist who receives an award on the same night that he is visited by a very unhappy ex-patient. After this encounter, Crowe takes on the task of curing a young boy with the same ills as the ex-patient. This boy \"sees dead people\". Crowe spends a lot of time with the boy (Cole) much to the dismay of his wife. Cole's mom is at her wit's end with what to do about her son's increasing problems. Crowe is the boy's only hope.","Language":"English, Latin, Spanish","Country":"USA","Awards":"Nominated for 6 Oscars. Another 35 wins & 42 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTc2MTQxNDI5MV5BMl5BanBnXkFtZTYwNjkzMDc4._V1_SX300.jpg","Metascore":"64","imdbRating":"8.2","imdbVotes":"638,105","imdbID":"tt0167404","Type":"movie","Response":"True"},
	{"Title":"Rush","Year":"2013","Rated":"R","Released":"27 Sep 2013","Runtime":"123 min","Genre":"Action, Biography, Drama","Director":"Ron Howard","Writer":"Peter Morgan","Actors":"Chris Hemsworth, Daniel Brühl, Olivia Wilde, Alexandra Maria Lara","Plot":"Set against the sexy, glamorous golden age of Formula 1 racing in the 1970s, the film is based on the true story of a great sporting rivalry between handsome English playboy James Hunt (Hemsworth), and his methodical, brilliant opponent, Austrian driver Niki Lauda (Bruhl). The story follows their distinctly different personal styles on and off the track, their loves and the astonishing 1976 season in which both drivers were willing to risk everything to become world champion in a sport with no margin for error: if you make a mistake, you die.","Language":"English, German, Italian, French, Spanish","Country":"UK, Germany, USA","Awards":"Nominated for 2 Golden Globes. Another 8 wins & 50 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQyMDE0MTY0OV5BMl5BanBnXkFtZTcwMjI2OTI0OQ@@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.2","imdbVotes":"263,143","imdbID":"tt1979320","Type":"movie","Response":"True"},
	{"Title":"Kill Bill: Vol. 1","Year":"2003","Rated":"R","Released":"10 Oct 2003","Runtime":"111 min","Genre":"Action","Director":"Quentin Tarantino","Writer":"Quentin Tarantino, Quentin Tarantino (character The Bride), Uma Thurman (character The Bride)","Actors":"Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah","Plot":"The lead character, called 'The Bride,' was a member of the Deadly Viper Assassination Squad, led by her lover 'Bill.' Upon realizing she was pregnant with Bill's child, 'The Bride' decided to escape her life as a killer. She fled to Texas, met a young man, who, on the day of their wedding rehearsal was gunned down by an angry and jealous Bill (with the assistance of the Deadly Viper Assassination Squad). Four years later, 'The Bride' wakes from a coma, and discovers her baby is gone. She, then, decides to seek revenge upon the five people who destroyed her life and killed her baby. The saga of Kill Bill Volume I begins.","Language":"English, Japanese, French","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 23 wins & 64 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTU1NDg1Mzg4M15BMl5BanBnXkFtZTYwMDExOTc3._V1_SX300.jpg","Metascore":"69","imdbRating":"8.1","imdbVotes":"650,502","imdbID":"tt0266697","Type":"movie","Response":"True"},
	{"Title":"Stand by Me","Year":"1986","Rated":"R","Released":"22 Aug 1986","Runtime":"89 min","Genre":"Adventure, Drama","Director":"Rob Reiner","Writer":"Stephen King (novel), Raynold Gideon (screenplay), Bruce A. Evans (screenplay)","Actors":"Wil Wheaton, River Phoenix, Corey Feldman, Jerry O'Connell","Plot":"It's the summer of 1959 in Castlerock, Oregon and four 12 year-old boys - Gordie, Chris, Teddy and Vern - are fast friends. After learning of the general location of the body of a local boy who has been missing for several days, they set off into woods to see it. Along the way, they learn about themselves, the meaning of friendship and the need to stand up for what is right.","Language":"English","Country":"USA","Awards":"Nominated for 1 Oscar. Another 4 wins & 10 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDk2MTkyMTA1OF5BMl5BanBnXkFtZTcwOTc2Njk3OA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.1","imdbVotes":"245,774","imdbID":"tt0092005","Type":"movie","Response":"True"},
	{"Title":"The Bourne Ultimatum","Year":"2007","Rated":"PG-13","Released":"03 Aug 2007","Runtime":"115 min","Genre":"Action, Thriller","Director":"Paul Greengrass","Writer":"Tony Gilroy (screenplay), Scott Z. Burns (screenplay), George Nolfi (screenplay), Tony Gilroy (screen story), Robert Ludlum (novel)","Actors":"Matt Damon, Julia Stiles, David Strathairn, Scott Glenn","Plot":"Bourne is once again brought out of hiding, this time inadvertently by London-based reporter Simon Ross who is trying to unveil Operation Blackbriar--an upgrade to Project Treadstone--in a series of newspaper columns. Bourne sets up a meeting with Ross and realizes instantly they're being scanned. Information from the reporter stirs a new set of memories, and Bourne must finally, ultimately, uncover his dark past whilst dodging The Company's best efforts in trying to eradicate him.","Language":"English, French, Arabic, Russian, Spanish","Country":"USA, Germany","Awards":"Won 3 Oscars. Another 25 wins & 35 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTgzNjMwOTM3N15BMl5BanBnXkFtZTcwMzA5MDY0MQ@@._V1_SX300.jpg","Metascore":"85","imdbRating":"8.1","imdbVotes":"436,387","imdbID":"tt0440963","Type":"movie","Response":"True"},
	{"Title":"Shutter Island","Year":"2010","Rated":"R","Released":"19 Feb 2010","Runtime":"138 min","Genre":"Mystery, Thriller","Director":"Martin Scorsese","Writer":"Laeta Kalogridis (screenplay), Dennis Lehane (novel)","Actors":"Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley, Max von Sydow","Plot":"It's 1954, and up-and-coming U.S. marshal Teddy Daniels is assigned to investigate the disappearance of a patient from Boston's Shutter Island Ashecliffe Hospital. He's been pushing for an assignment on the island for personal reasons, but before long he wonders whether he hasn't been brought there as part of a twisted plot by hospital doctors whose radical treatments range from unethical to illegal to downright sinister. Teddy's shrewd investigating skills soon provide a promising lead, but the hospital refuses him access to records he suspects would break the case wide open. As a hurricane cuts off communication with the mainland, more dangerous criminals \"escape\" in the confusion, and the puzzling, improbable clues multiply, Teddy begins to doubt everything - his memory, his partner, even his own sanity.","Language":"English, German","Country":"USA","Awards":"7 wins & 53 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTMxMTIyNzMxMV5BMl5BanBnXkFtZTcwOTc4OTI3Mg@@._V1_SX300.jpg","Metascore":"63","imdbRating":"8.1","imdbVotes":"679,494","imdbID":"tt1130884","Type":"movie","Response":"True"},
	{"Title":"Donnie Darko","Year":"2001","Rated":"R","Released":"26 Oct 2001","Runtime":"113 min","Genre":"Drama, Sci-Fi","Director":"Richard Kelly","Writer":"Richard Kelly","Actors":"Jake Gyllenhaal, Holmes Osborne, Maggie Gyllenhaal, Daveigh Chase","Plot":"Donnie Darko doesn't get along too well with his family, his teachers and his classmates; but he does manage to find a sympathetic friend in Gretchen, who agrees to date him. He has a compassionate psychiatrist, who discovers hypnosis is the means to unlock hidden secrets. His other companion may not be a true ally. Donnie has a friend named Frank - a large bunny which only Donnie can see. When an engine falls off a plane and destroys his bedroom, Donnie is not there. Both the event, and Donnie's escape, seem to have been caused by supernatural events. Donnie's mental illness, if such it is, may never allow him to find out for sure.","Language":"English","Country":"USA","Awards":"11 wins & 14 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTczMzE4Nzk3N15BMl5BanBnXkFtZTcwNDg5Mjc4NA@@._V1_SX300.jpg","Metascore":"71","imdbRating":"8.1","imdbVotes":"527,528","imdbID":"tt0246578","Type":"movie","Response":"True"},
    {"Title":"The Avengers","Year":"2012","Rated":"PG-13","Released":"04 May 2012","Runtime":"143 min","Genre":"Action, Adventure, Sci-Fi","Director":"Joss Whedon","Writer":"Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)","Actors":"Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth","Plot":"Nick Fury is director of S.H.I.E.L.D, an international peace keeping agency. The agency is a who's who of Marvel Super Heroes, with Iron Man, The Incredible Hulk, Thor, Captain America, Hawkeye and Black Widow. When global security is threatened by Loki and his cohorts, Nick Fury and his team will need all their powers to save the world from disaster.","Language":"English, Russian","Country":"USA","Awards":"Nominated for 1 Oscar. Another 32 wins & 67 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg","Metascore":"69","imdbRating":"8.1","imdbVotes":"877,226","imdbID":"tt0848228","Type":"movie","Response":"True"},
	{"Title":"The Terminator","Year":"1984","Rated":"R","Released":"26 Oct 1984","Runtime":"107 min","Genre":"Action, Sci-Fi","Director":"James Cameron","Writer":"James Cameron, Gale Anne Hurd, William Wisher Jr. (additional dialogue)","Actors":"Arnold Schwarzenegger, Michael Biehn, Linda Hamilton, Paul Winfield","Plot":"A cyborg is sent from the future on a deadly mission. He has to kill Sarah Connor, a young woman whose life will have a great significance in years to come. Sarah has only one protector - Kyle Reese - also sent from the future. The Terminator uses his exceptional intelligence and strength to find Sarah, but is there any way to stop the seemingly indestructible cyborg ?","Language":"English, Spanish","Country":"UK, USA","Awards":"5 wins & 6 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BODE1MDczNTUxOV5BMl5BanBnXkFtZTcwMTA0NDQyNA@@._V1_SX300.jpg","Metascore":"83","imdbRating":"8.1","imdbVotes":"534,346","imdbID":"tt0088247","Type":"movie","Response":"True"},
	{"Title":"Jaws","Year":"1975","Rated":"PG","Released":"20 Jun 1975","Runtime":"124 min","Genre":"Adventure, Drama, Thriller","Director":"Steven Spielberg","Writer":"Peter Benchley (screenplay), Carl Gottlieb (screenplay), Peter Benchley (based on the novel by)","Actors":"Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary","Plot":"It's a hot summer on Amity Island, a small community whose main business is its beaches. When new Sheriff Martin Brody discovers the remains of a shark attack victim, his first inclination is to close the beaches to swimmers. This doesn't sit well with Mayor Larry Vaughn and several of the local businessmen. Brody backs down to his regret as that weekend a young boy is killed by the predator. The dead boy's mother puts out a bounty on the shark and Amity is soon swamped with amateur hunters and fisherman hoping to cash in on the reward. A local fisherman with much experience hunting sharks, Quint, offers to hunt down the creature for a hefty fee. Soon Quint, Brody and Matt Hooper from the Oceanographic Institute are at sea hunting the Great White shark. As Brody succinctly surmises after their first encounter with the creature, they're going to need a bigger boat.","Language":"English","Country":"USA","Awards":"Won 3 Oscars. Another 10 wins & 14 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDcxODkyMjY4MF5BMl5BanBnXkFtZTgwOTk5NTc5MDE@._V1_SX300.jpg","Metascore":"79","imdbRating":"8.1","imdbVotes":"368,812","imdbID":"tt0073195","Type":"movie","Response":"True"},
	{"Title":"Guardians of the Galaxy","Year":"2014","Rated":"PG-13","Released":"01 Aug 2014","Runtime":"121 min","Genre":"Action, Adventure, Sci-Fi","Director":"James Gunn","Writer":"James Gunn, Nicole Perlman, Dan Abnett (comic book), Andy Lanning (comic book)","Actors":"Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel","Plot":"After stealing a mysterious orb in the far reaches of outer space, Peter Quill from Earth, is now the main target of a manhunt led by the villain known as Ronan the Accuser. To help fight Ronan and his team and save the galaxy from his power, Quill creates a team of space heroes known as the \"Guardians of the Galaxy\" to save the world.","Language":"English","Country":"USA, UK","Awards":"Nominated for 2 Oscars. Another 42 wins & 81 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SX300.jpg","Metascore":"76","imdbRating":"8.1","imdbVotes":"539,583","imdbID":"tt2015381","Type":"movie","Response":"True"},
	{"Title":"Monsters, Inc.","Year":"2001","Rated":"G","Released":"02 Nov 2001","Runtime":"92 min","Genre":"Animation, Adventure, Comedy","Director":"Pete Docter, David Silverman, Lee Unkrich","Writer":"Pete Docter (original story by), Jill Culton (original story by), Jeff Pidgeon (original story by), Ralph Eggleston (original story by), Andrew Stanton (screenplay), Daniel Gerson (screenplay), Robert L. Baird (additional screenplay material), Rhett Reese (additional screenplay material), Jonathan Roberts (additional screenplay material)","Actors":"John Goodman, Billy Crystal, Mary Gibbs, Steve Buscemi","Plot":"A city of monsters with no humans called Monstropolis centers around the city's power company, Monsters, Inc. The lovable, confident, tough, furry blue behemoth-like giant monster named James P. Sullivan (better known as Sulley) and his wisecracking best friend, short, green cyclops monster Mike Wazowski, discover what happens when the real world interacts with theirs in the form of a 2-year-old baby girl dubbed \"Boo,\" who accidentally sneaks into the monster world with Sulley one night. And now it's up to Sulley and Mike to send Boo back in her door before anybody finds out, especially two evil villains such as Sulley's main rival as a scarer, chameleon-like Randall (a monster that Boo is very afraid of), who possesses the ability to change the color of his skin, and Mike and Sulley's boss Mr. Waternoose, the chairman and chief executive officer of Monsters, Inc.","Language":"English","Country":"USA","Awards":"Won 1 Oscar. Another 16 wins & 34 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_SX300.jpg","Metascore":"78","imdbRating":"8.1","imdbVotes":"509,260","imdbID":"tt0198781","Type":"movie","Response":"True"},
	{"Title":"Harry Potter and the Deathly Hallows: Part 2","Year":"2011","Rated":"PG-13","Released":"15 Jul 2011","Runtime":"130 min","Genre":"Adventure, Drama, Fantasy","Director":"David Yates","Writer":"Steve Kloves (screenplay), J.K. Rowling (novel)","Actors":"Ralph Fiennes, Michael Gambon, Alan Rickman, Daniel Radcliffe","Plot":"Harry, Ron, and Hermione continue their quest of finding and destroying the Dark Lord's three remaining Horcruxes, the magical items responsible for his immortality. But as the mystical Deathly Hallows are uncovered, and Voldemort finds out about their mission, the biggest battle begins and life as they know it will never be the same again.","Language":"English","Country":"USA, UK","Awards":"Nominated for 3 Oscars. Another 48 wins & 77 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY2MTk3MDQ1N15BMl5BanBnXkFtZTcwMzI4NzA2NQ@@._V1_SX300.jpg","Metascore":"87","imdbRating":"8.1","imdbVotes":"470,311","imdbID":"tt1201607","Type":"movie","Response":"True"},
	{"Title":"The Truman Show","Year":"1998","Rated":"PG","Released":"05 Jun 1998","Runtime":"103 min","Genre":"Drama","Director":"Peter Weir","Writer":"Andrew Niccol","Actors":"Jim Carrey, Laura Linney, Noah Emmerich, Natascha McElhone","Plot":"In this movie, Truman is a man whose life is a fake one... The place he lives is in fact a big studio with hidden cameras everywhere, and all his friends and people around him, are actors who play their roles in the most popular TV-series in the world: The Truman Show. Truman thinks that he is an ordinary man with an ordinary life and has no idea about how he is exploited. Until one day... he finds out everything. Will he react?","Language":"English","Country":"USA","Awards":"Nominated for 3 Oscars. Another 41 wins & 58 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTM4NjY2MTEzM15BMl5BanBnXkFtZTcwMTk2Njk3OA@@._V1_SX300.jpg","Metascore":"90","imdbRating":"8.1","imdbVotes":"592,268","imdbID":"tt0120382","Type":"movie","Response":"True"},
	{"Title":"Rocky","Year":"1976","Rated":"PG","Released":"03 Dec 1976","Runtime":"119 min","Genre":"Drama, Sport","Director":"John G. Avildsen","Writer":"Sylvester Stallone","Actors":"Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers","Plot":"Rocky Balboa is a struggling boxer trying to make the big time, working as a debt collector for a pittance. When heavyweight champion Apollo Creed visits Philadelphia, his managers want to set up an exhibition match between Creed and a struggling boxer, touting the fight as a chance for a \"nobody\" to become a \"somebody\". The match is supposed to be easily won by Creed, but someone forgot to tell Rocky, who sees this as his only shot at the big time.","Language":"English","Country":"USA","Awards":"Won 3 Oscars. Another 17 wins & 20 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY5MDMzODUyOF5BMl5BanBnXkFtZTcwMTQ3NTMyNA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.1","imdbVotes":"320,993","imdbID":"tt0075148","Type":"movie","Response":"True"},
	{"Title":"The Imitation Game","Year":"2014","Rated":"PG-13","Released":"25 Dec 2014","Runtime":"114 min","Genre":"Biography, Drama, Thriller","Director":"Morten Tyldum","Writer":"Graham Moore, Andrew Hodges (book)","Actors":"Benedict Cumberbatch, Keira Knightley, Matthew Goode, Rory Kinnear","Plot":"Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain's top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.","Language":"English, German","Country":"UK, USA","Awards":"Won 1 Oscar. Another 52 wins & 125 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDkwNTEyMzkzNl5BMl5BanBnXkFtZTgwNTAwNzk3MjE@._V1_SX300.jpg","Metascore":"73","imdbRating":"8.1","imdbVotes":"337,941","imdbID":"tt2084970","Type":"movie","Response":"True"},
	{"Title":"Blade Runner","Year":"1982","Rated":"R","Released":"25 Jun 1982","Runtime":"117 min","Genre":"Sci-Fi, Thriller","Director":"Ridley Scott","Writer":"Hampton Fancher (screenplay), David Webb Peoples (screenplay), Philip K. Dick (novel)","Actors":"Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos","Plot":"In a cyberpunk vision of the future, man has developed the technology to create replicants, human clones used to serve in the colonies outside Earth but with fixed lifespans. In Los Angeles, 2019, Deckard is a Blade Runner, a cop who specializes in terminating replicants. Originally in retirement, he is forced to re-enter the force when four replicants escape from an off-world colony to Earth.","Language":"English, German, Cantonese, Japanese, Hungarian","Country":"USA, Hong Kong, UK","Awards":"Nominated for 2 Oscars. Another 11 wins & 15 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTA4MDQxNTk2NDheQTJeQWpwZ15BbWU3MDE2NjIyODk@._V1_SX300.jpg","Metascore":"88","imdbRating":"8.2","imdbVotes":"419,589","imdbID":"tt0083658","Type":"movie","Response":"True"},
	{"Title":"The Wolf of Wall Street","Year":"2013","Rated":"R","Released":"25 Dec 2013","Runtime":"180 min","Genre":"Biography, Comedy, Crime","Director":"Martin Scorsese","Writer":"Terence Winter (screenplay), Jordan Belfort (book)","Actors":"Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey","Plot":"In The Wolf of Wall Street DiCaprio plays Belfort, a Long Island penny stockbroker who served 22 months in prison for defrauding investors in a massive 1990s securities scam that involved widespread corruption on Wall Street and in the corporate banking world, including shoe designer Steve Madden.","Language":"English, French","Country":"USA","Awards":"Nominated for 5 Oscars. Another 47 wins & 128 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.2","imdbVotes":"632,551","imdbID":"tt0993846","Type":"movie","Response":"True"},
	{"Title":"Warrior","Year":"2011","Rated":"PG-13","Released":"09 Sep 2011","Runtime":"140 min","Genre":"Drama, Sport","Director":"Gavin O'Connor","Writer":"Gavin O'Connor (screenplay), Anthony Tambakis (screenplay), Cliff Dorfman (screenplay), Gavin O'Connor (story), Cliff Dorfman (story)","Actors":"Joel Edgerton, Tom Hardy, Nick Nolte, Jennifer Morrison","Plot":"Two brothers face the fight of a lifetime - and the wreckage of their broken family - within the brutal, high-stakes world of Mixed Martial Arts (MMA) fighting in Lionsgate's action/drama, WARRIOR. An ex-Marine haunted by a tragic past, Tommy Riordan returns to his hometown of Pittsburgh and enlists his father, a recovered alcoholic and his former coach, to train him for an MMA tournament awarding the biggest purse in the history of the sport. As Tommy blazes a violent path towards the title prize, his brother, Brendan, a former MMA fighter unable to make ends meet as a public school teacher, returns to the amateur ring to provide for his family. Even though years have passed, recriminations and past betrayals keep Brendan bitterly estranged from both Tommy and his father. But when Brendan's unlikely rise as an underdog sets him on a collision course with Tommy, the two brothers must finally confront the forces that tore them apart, all the while waging the most intense, winner-takes-all battle of their lives.","Language":"English, Spanish","Country":"USA","Awards":"Nominated for 1 Oscar. Another 6 wins & 17 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk4ODk5MTMyNV5BMl5BanBnXkFtZTcwMDMyNTg0Ng@@._V1_SX300.jpg","Metascore":"71","imdbRating":"8.2","imdbVotes":"292,471","imdbID":"tt1291584","Type":"movie","Response":"True"},
	{"Title":"Gran Torino","Year":"2008","Rated":"R","Released":"09 Jan 2009","Runtime":"116 min","Genre":"Drama","Director":"Clint Eastwood","Writer":"Nick Schenk (screenplay), Dave Johannson (story), Nick Schenk (story)","Actors":"Clint Eastwood, Christopher Carley, Bee Vang, Ahney Her","Plot":"Walt Kowalski is a widower who holds onto his prejudices despite the changes in his Michigan neighborhood and the world around him. Kowalski is a grumpy, tough-minded, unhappy old man who can't get along with either his kids or his neighbors. He is a Korean War veteran whose prize possession is a 1972 Gran Torino he keeps in mint condition. When his neighbor Thao, a young Hmong teenager under pressure from his gang member cousin, tries to steal his Gran Torino, Kowalski sets out to reform the youth. Drawn against his will into the life of Thao's family, Kowalski is soon taking steps to protect them from the gangs that infest their neighborhood.","Language":"English, Hmong","Country":"USA, Germany","Awards":"Nominated for 1 Golden Globe. Another 22 wins & 10 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQyMTczMTAxMl5BMl5BanBnXkFtZTcwOTc1ODE0Mg@@._V1_SX300.jpg","Metascore":"72","imdbRating":"8.2","imdbVotes":"506,194","imdbID":"tt1205489","Type":"movie","Response":"True"},
	{"Title":"V for Vendetta","Year":"2005","Rated":"R","Released":"17 Mar 2006","Runtime":"132 min","Genre":"Action, Drama, Thriller","Director":"James McTeigue","Writer":"Andy Wachowski (screenplay), Lana Wachowski (screenplay), David Lloyd (graphic novel art)","Actors":"Natalie Portman, Hugo Weaving, Stephen Rea, Stephen Fry","Plot":"Tells the story of Evey Hammond and her unlikely but instrumental part in bringing down the fascist government that has taken control of a futuristic Great Britain. Saved from a life-and-death situation by a man in a Guy Fawkes mask who calls himself V, she learns a general summary of V's past and, after a time, decides to help him bring down those who committed the atrocities that led to Britain being in the shape that it is in.","Language":"English","Country":"USA, UK, Germany","Awards":"10 wins & 23 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_SX300.jpg","Metascore":"62","imdbRating":"8.2","imdbVotes":"709,179","imdbID":"tt0434409","Type":"movie","Response":"True"},
	{"Title":"A Beautiful Mind","Year":"2001","Rated":"PG-13","Released":"04 Jan 2002","Runtime":"135 min","Genre":"Biography, Drama","Director":"Ron Howard","Writer":"Akiva Goldsman, Sylvia Nasar (book)","Actors":"Russell Crowe, Ed Harris, Jennifer Connelly, Christopher Plummer","Plot":"From the heights of notoriety to the depths of depravity, John Forbes Nash, Jr. experienced it all. A mathematical genius, he made an astonishing discovery early in his career and stood on the brink of international acclaim. But the handsome and arrogant Nash soon found himself on a painful and harrowing journey of self-discovery. After many years of struggle, he eventually triumphed over his tragedy, and finally - late in life - received the Nobel Prize.","Language":"English","Country":"USA","Awards":"Won 4 Oscars. Another 32 wins & 58 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ4MDI2MzkwMl5BMl5BanBnXkFtZTYwMjk0NTA5._V1_SX300.jpg","Metascore":"72","imdbRating":"8.2","imdbVotes":"532,561","imdbID":"tt0268978","Type":"movie","Response":"True"},
	{"Title":"How to Train Your Dragon","Year":"2010","Rated":"PG","Released":"26 Mar 2010","Runtime":"98 min","Genre":"Animation, Adventure, Family","Director":"Dean DeBlois, Chris Sanders","Writer":"William Davies (screenplay), Dean DeBlois (screenplay), Chris Sanders (screenplay), Cressida Cowell (book)","Actors":"Jay Baruchel, Gerard Butler, Craig Ferguson, America Ferrera","Plot":"Long ago up North on the Island of Berk, the young Viking, Hiccup, wants to join his town's fight against the dragons that continually raid their town. However, his macho father and village leader, Stoik the Vast, will not allow his small, clumsy, but inventive son to do so. Regardless, Hiccup ventures out into battle and downs a mysterious Night Fury dragon with his invention, but can't bring himself to kill it. Instead, Hiccup and the dragon, whom he dubs Toothless, begin a friendship that would open up both their worlds as the observant boy learns that his people have misjudged the species. But even as the two each take flight in their own way, they find that they must fight the destructive ignorance plaguing their world.","Language":"English","Country":"USA","Awards":"Nominated for 2 Oscars. Another 30 wins & 51 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.2","imdbVotes":"421,636","imdbID":"tt0892769","Type":"movie","Response":"True"},
	{"Title":"Gone Girl","Year":"2014","Rated":"R","Released":"03 Oct 2014","Runtime":"149 min","Genre":"Drama, Mystery, Thriller","Director":"David Fincher","Writer":"Gillian Flynn (screenplay), Gillian Flynn (novel)","Actors":"Ben Affleck, Rosamund Pike, Neil Patrick Harris, Tyler Perry","Plot":"On the occasion of his fifth wedding anniversary, Nick Dunne reports that his wife, Amy, has gone missing. Under pressure from the police and a growing media frenzy, Nick's portrait of a blissful union begins to crumble. Soon his lies, deceits and strange behavior have everyone asking the same dark question: Did Nick Dunne kill his wife?","Language":"English","Country":"USA","Awards":"Nominated for 1 Oscar. Another 69 wins & 136 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzU1NzE3MjE@._V1_SX300.jpg","Metascore":"79","imdbRating":"8.2","imdbVotes":"456,460","imdbID":"tt2267998","Type":"movie","Response":"True"},
	{"Title":"The Sixth Sense","Year":"1999","Rated":"PG-13","Released":"06 Aug 1999","Runtime":"107 min","Genre":"Drama, Mystery, Thriller","Director":"M. Night Shyamalan","Writer":"M. Night Shyamalan","Actors":"Bruce Willis, Haley Joel Osment, Toni Collette, Olivia Williams","Plot":"Malcom Crowe is a child psychologist who receives an award on the same night that he is visited by a very unhappy ex-patient. After this encounter, Crowe takes on the task of curing a young boy with the same ills as the ex-patient. This boy \"sees dead people\". Crowe spends a lot of time with the boy (Cole) much to the dismay of his wife. Cole's mom is at her wit's end with what to do about her son's increasing problems. Crowe is the boy's only hope.","Language":"English, Latin, Spanish","Country":"USA","Awards":"Nominated for 6 Oscars. Another 35 wins & 42 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTc2MTQxNDI5MV5BMl5BanBnXkFtZTYwNjkzMDc4._V1_SX300.jpg","Metascore":"64","imdbRating":"8.2","imdbVotes":"638,105","imdbID":"tt0167404","Type":"movie","Response":"True"},
	{"Title":"Rush","Year":"2013","Rated":"R","Released":"27 Sep 2013","Runtime":"123 min","Genre":"Action, Biography, Drama","Director":"Ron Howard","Writer":"Peter Morgan","Actors":"Chris Hemsworth, Daniel Brühl, Olivia Wilde, Alexandra Maria Lara","Plot":"Set against the sexy, glamorous golden age of Formula 1 racing in the 1970s, the film is based on the true story of a great sporting rivalry between handsome English playboy James Hunt (Hemsworth), and his methodical, brilliant opponent, Austrian driver Niki Lauda (Bruhl). The story follows their distinctly different personal styles on and off the track, their loves and the astonishing 1976 season in which both drivers were willing to risk everything to become world champion in a sport with no margin for error: if you make a mistake, you die.","Language":"English, German, Italian, French, Spanish","Country":"UK, Germany, USA","Awards":"Nominated for 2 Golden Globes. Another 8 wins & 50 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQyMDE0MTY0OV5BMl5BanBnXkFtZTcwMjI2OTI0OQ@@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.2","imdbVotes":"263,143","imdbID":"tt1979320","Type":"movie","Response":"True"},
	{"Title":"Kill Bill: Vol. 1","Year":"2003","Rated":"R","Released":"10 Oct 2003","Runtime":"111 min","Genre":"Action","Director":"Quentin Tarantino","Writer":"Quentin Tarantino, Quentin Tarantino (character The Bride), Uma Thurman (character The Bride)","Actors":"Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah","Plot":"The lead character, called 'The Bride,' was a member of the Deadly Viper Assassination Squad, led by her lover 'Bill.' Upon realizing she was pregnant with Bill's child, 'The Bride' decided to escape her life as a killer. She fled to Texas, met a young man, who, on the day of their wedding rehearsal was gunned down by an angry and jealous Bill (with the assistance of the Deadly Viper Assassination Squad). Four years later, 'The Bride' wakes from a coma, and discovers her baby is gone. She, then, decides to seek revenge upon the five people who destroyed her life and killed her baby. The saga of Kill Bill Volume I begins.","Language":"English, Japanese, French","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 23 wins & 64 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTU1NDg1Mzg4M15BMl5BanBnXkFtZTYwMDExOTc3._V1_SX300.jpg","Metascore":"69","imdbRating":"8.1","imdbVotes":"650,502","imdbID":"tt0266697","Type":"movie","Response":"True"},
	{"Title":"Stand by Me","Year":"1986","Rated":"R","Released":"22 Aug 1986","Runtime":"89 min","Genre":"Adventure, Drama","Director":"Rob Reiner","Writer":"Stephen King (novel), Raynold Gideon (screenplay), Bruce A. Evans (screenplay)","Actors":"Wil Wheaton, River Phoenix, Corey Feldman, Jerry O'Connell","Plot":"It's the summer of 1959 in Castlerock, Oregon and four 12 year-old boys - Gordie, Chris, Teddy and Vern - are fast friends. After learning of the general location of the body of a local boy who has been missing for several days, they set off into woods to see it. Along the way, they learn about themselves, the meaning of friendship and the need to stand up for what is right.","Language":"English","Country":"USA","Awards":"Nominated for 1 Oscar. Another 4 wins & 10 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDk2MTkyMTA1OF5BMl5BanBnXkFtZTcwOTc2Njk3OA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.1","imdbVotes":"245,774","imdbID":"tt0092005","Type":"movie","Response":"True"},
	{"Title":"The Bourne Ultimatum","Year":"2007","Rated":"PG-13","Released":"03 Aug 2007","Runtime":"115 min","Genre":"Action, Thriller","Director":"Paul Greengrass","Writer":"Tony Gilroy (screenplay), Scott Z. Burns (screenplay), George Nolfi (screenplay), Tony Gilroy (screen story), Robert Ludlum (novel)","Actors":"Matt Damon, Julia Stiles, David Strathairn, Scott Glenn","Plot":"Bourne is once again brought out of hiding, this time inadvertently by London-based reporter Simon Ross who is trying to unveil Operation Blackbriar--an upgrade to Project Treadstone--in a series of newspaper columns. Bourne sets up a meeting with Ross and realizes instantly they're being scanned. Information from the reporter stirs a new set of memories, and Bourne must finally, ultimately, uncover his dark past whilst dodging The Company's best efforts in trying to eradicate him.","Language":"English, French, Arabic, Russian, Spanish","Country":"USA, Germany","Awards":"Won 3 Oscars. Another 25 wins & 35 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTgzNjMwOTM3N15BMl5BanBnXkFtZTcwMzA5MDY0MQ@@._V1_SX300.jpg","Metascore":"85","imdbRating":"8.1","imdbVotes":"436,387","imdbID":"tt0440963","Type":"movie","Response":"True"},
	{"Title":"Shutter Island","Year":"2010","Rated":"R","Released":"19 Feb 2010","Runtime":"138 min","Genre":"Mystery, Thriller","Director":"Martin Scorsese","Writer":"Laeta Kalogridis (screenplay), Dennis Lehane (novel)","Actors":"Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley, Max von Sydow","Plot":"It's 1954, and up-and-coming U.S. marshal Teddy Daniels is assigned to investigate the disappearance of a patient from Boston's Shutter Island Ashecliffe Hospital. He's been pushing for an assignment on the island for personal reasons, but before long he wonders whether he hasn't been brought there as part of a twisted plot by hospital doctors whose radical treatments range from unethical to illegal to downright sinister. Teddy's shrewd investigating skills soon provide a promising lead, but the hospital refuses him access to records he suspects would break the case wide open. As a hurricane cuts off communication with the mainland, more dangerous criminals \"escape\" in the confusion, and the puzzling, improbable clues multiply, Teddy begins to doubt everything - his memory, his partner, even his own sanity.","Language":"English, German","Country":"USA","Awards":"7 wins & 53 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTMxMTIyNzMxMV5BMl5BanBnXkFtZTcwOTc4OTI3Mg@@._V1_SX300.jpg","Metascore":"63","imdbRating":"8.1","imdbVotes":"679,494","imdbID":"tt1130884","Type":"movie","Response":"True"},
	{"Title":"Donnie Darko","Year":"2001","Rated":"R","Released":"26 Oct 2001","Runtime":"113 min","Genre":"Drama, Sci-Fi","Director":"Richard Kelly","Writer":"Richard Kelly","Actors":"Jake Gyllenhaal, Holmes Osborne, Maggie Gyllenhaal, Daveigh Chase","Plot":"Donnie Darko doesn't get along too well with his family, his teachers and his classmates; but he does manage to find a sympathetic friend in Gretchen, who agrees to date him. He has a compassionate psychiatrist, who discovers hypnosis is the means to unlock hidden secrets. His other companion may not be a true ally. Donnie has a friend named Frank - a large bunny which only Donnie can see. When an engine falls off a plane and destroys his bedroom, Donnie is not there. Both the event, and Donnie's escape, seem to have been caused by supernatural events. Donnie's mental illness, if such it is, may never allow him to find out for sure.","Language":"English","Country":"USA","Awards":"11 wins & 14 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTczMzE4Nzk3N15BMl5BanBnXkFtZTcwNDg5Mjc4NA@@._V1_SX300.jpg","Metascore":"71","imdbRating":"8.1","imdbVotes":"527,528","imdbID":"tt0246578","Type":"movie","Response":"True"},
	{"Title":"The Avengers","Year":"2012","Rated":"PG-13","Released":"04 May 2012","Runtime":"143 min","Genre":"Action, Adventure, Sci-Fi","Director":"Joss Whedon","Writer":"Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)","Actors":"Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth","Plot":"Nick Fury is director of S.H.I.E.L.D, an international peace keeping agency. The agency is a who's who of Marvel Super Heroes, with Iron Man, The Incredible Hulk, Thor, Captain America, Hawkeye and Black Widow. When global security is threatened by Loki and his cohorts, Nick Fury and his team will need all their powers to save the world from disaster.","Language":"English, Russian","Country":"USA","Awards":"Nominated for 1 Oscar. Another 32 wins & 67 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg","Metascore":"69","imdbRating":"8.1","imdbVotes":"877,226","imdbID":"tt0848228","Type":"movie","Response":"True"},
	{"Title":"The Terminator","Year":"1984","Rated":"R","Released":"26 Oct 1984","Runtime":"107 min","Genre":"Action, Sci-Fi","Director":"James Cameron","Writer":"James Cameron, Gale Anne Hurd, William Wisher Jr. (additional dialogue)","Actors":"Arnold Schwarzenegger, Michael Biehn, Linda Hamilton, Paul Winfield","Plot":"A cyborg is sent from the future on a deadly mission. He has to kill Sarah Connor, a young woman whose life will have a great significance in years to come. Sarah has only one protector - Kyle Reese - also sent from the future. The Terminator uses his exceptional intelligence and strength to find Sarah, but is there any way to stop the seemingly indestructible cyborg ?","Language":"English, Spanish","Country":"UK, USA","Awards":"5 wins & 6 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BODE1MDczNTUxOV5BMl5BanBnXkFtZTcwMTA0NDQyNA@@._V1_SX300.jpg","Metascore":"83","imdbRating":"8.1","imdbVotes":"534,346","imdbID":"tt0088247","Type":"movie","Response":"True"},
	{"Title":"Jaws","Year":"1975","Rated":"PG","Released":"20 Jun 1975","Runtime":"124 min","Genre":"Adventure, Drama, Thriller","Director":"Steven Spielberg","Writer":"Peter Benchley (screenplay), Carl Gottlieb (screenplay), Peter Benchley (based on the novel by)","Actors":"Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary","Plot":"It's a hot summer on Amity Island, a small community whose main business is its beaches. When new Sheriff Martin Brody discovers the remains of a shark attack victim, his first inclination is to close the beaches to swimmers. This doesn't sit well with Mayor Larry Vaughn and several of the local businessmen. Brody backs down to his regret as that weekend a young boy is killed by the predator. The dead boy's mother puts out a bounty on the shark and Amity is soon swamped with amateur hunters and fisherman hoping to cash in on the reward. A local fisherman with much experience hunting sharks, Quint, offers to hunt down the creature for a hefty fee. Soon Quint, Brody and Matt Hooper from the Oceanographic Institute are at sea hunting the Great White shark. As Brody succinctly surmises after their first encounter with the creature, they're going to need a bigger boat.","Language":"English","Country":"USA","Awards":"Won 3 Oscars. Another 10 wins & 14 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDcxODkyMjY4MF5BMl5BanBnXkFtZTgwOTk5NTc5MDE@._V1_SX300.jpg","Metascore":"79","imdbRating":"8.1","imdbVotes":"368,812","imdbID":"tt0073195","Type":"movie","Response":"True"},
	{"Title":"Guardians of the Galaxy","Year":"2014","Rated":"PG-13","Released":"01 Aug 2014","Runtime":"121 min","Genre":"Action, Adventure, Sci-Fi","Director":"James Gunn","Writer":"James Gunn, Nicole Perlman, Dan Abnett (comic book), Andy Lanning (comic book)","Actors":"Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel","Plot":"After stealing a mysterious orb in the far reaches of outer space, Peter Quill from Earth, is now the main target of a manhunt led by the villain known as Ronan the Accuser. To help fight Ronan and his team and save the galaxy from his power, Quill creates a team of space heroes known as the \"Guardians of the Galaxy\" to save the world.","Language":"English","Country":"USA, UK","Awards":"Nominated for 2 Oscars. Another 42 wins & 81 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SX300.jpg","Metascore":"76","imdbRating":"8.1","imdbVotes":"539,583","imdbID":"tt2015381","Type":"movie","Response":"True"},
	{"Title":"Monsters, Inc.","Year":"2001","Rated":"G","Released":"02 Nov 2001","Runtime":"92 min","Genre":"Animation, Adventure, Comedy","Director":"Pete Docter, David Silverman, Lee Unkrich","Writer":"Pete Docter (original story by), Jill Culton (original story by), Jeff Pidgeon (original story by), Ralph Eggleston (original story by), Andrew Stanton (screenplay), Daniel Gerson (screenplay), Robert L. Baird (additional screenplay material), Rhett Reese (additional screenplay material), Jonathan Roberts (additional screenplay material)","Actors":"John Goodman, Billy Crystal, Mary Gibbs, Steve Buscemi","Plot":"A city of monsters with no humans called Monstropolis centers around the city's power company, Monsters, Inc. The lovable, confident, tough, furry blue behemoth-like giant monster named James P. Sullivan (better known as Sulley) and his wisecracking best friend, short, green cyclops monster Mike Wazowski, discover what happens when the real world interacts with theirs in the form of a 2-year-old baby girl dubbed \"Boo,\" who accidentally sneaks into the monster world with Sulley one night. And now it's up to Sulley and Mike to send Boo back in her door before anybody finds out, especially two evil villains such as Sulley's main rival as a scarer, chameleon-like Randall (a monster that Boo is very afraid of), who possesses the ability to change the color of his skin, and Mike and Sulley's boss Mr. Waternoose, the chairman and chief executive officer of Monsters, Inc.","Language":"English","Country":"USA","Awards":"Won 1 Oscar. Another 16 wins & 34 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_SX300.jpg","Metascore":"78","imdbRating":"8.1","imdbVotes":"509,260","imdbID":"tt0198781","Type":"movie","Response":"True"},
	{"Title":"Harry Potter and the Deathly Hallows: Part 2","Year":"2011","Rated":"PG-13","Released":"15 Jul 2011","Runtime":"130 min","Genre":"Adventure, Drama, Fantasy","Director":"David Yates","Writer":"Steve Kloves (screenplay), J.K. Rowling (novel)","Actors":"Ralph Fiennes, Michael Gambon, Alan Rickman, Daniel Radcliffe","Plot":"Harry, Ron, and Hermione continue their quest of finding and destroying the Dark Lord's three remaining Horcruxes, the magical items responsible for his immortality. But as the mystical Deathly Hallows are uncovered, and Voldemort finds out about their mission, the biggest battle begins and life as they know it will never be the same again.","Language":"English","Country":"USA, UK","Awards":"Nominated for 3 Oscars. Another 48 wins & 77 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY2MTk3MDQ1N15BMl5BanBnXkFtZTcwMzI4NzA2NQ@@._V1_SX300.jpg","Metascore":"87","imdbRating":"8.1","imdbVotes":"470,311","imdbID":"tt1201607","Type":"movie","Response":"True"},
	{"Title":"The Truman Show","Year":"1998","Rated":"PG","Released":"05 Jun 1998","Runtime":"103 min","Genre":"Drama","Director":"Peter Weir","Writer":"Andrew Niccol","Actors":"Jim Carrey, Laura Linney, Noah Emmerich, Natascha McElhone","Plot":"In this movie, Truman is a man whose life is a fake one... The place he lives is in fact a big studio with hidden cameras everywhere, and all his friends and people around him, are actors who play their roles in the most popular TV-series in the world: The Truman Show. Truman thinks that he is an ordinary man with an ordinary life and has no idea about how he is exploited. Until one day... he finds out everything. Will he react?","Language":"English","Country":"USA","Awards":"Nominated for 3 Oscars. Another 41 wins & 58 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTM4NjY2MTEzM15BMl5BanBnXkFtZTcwMTk2Njk3OA@@._V1_SX300.jpg","Metascore":"90","imdbRating":"8.1","imdbVotes":"592,268","imdbID":"tt0120382","Type":"movie","Response":"True"},
	{"Title":"Rocky","Year":"1976","Rated":"PG","Released":"03 Dec 1976","Runtime":"119 min","Genre":"Drama, Sport","Director":"John G. Avildsen","Writer":"Sylvester Stallone","Actors":"Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers","Plot":"Rocky Balboa is a struggling boxer trying to make the big time, working as a debt collector for a pittance. When heavyweight champion Apollo Creed visits Philadelphia, his managers want to set up an exhibition match between Creed and a struggling boxer, touting the fight as a chance for a \"nobody\" to become a \"somebody\". The match is supposed to be easily won by Creed, but someone forgot to tell Rocky, who sees this as his only shot at the big time.","Language":"English","Country":"USA","Awards":"Won 3 Oscars. Another 17 wins & 20 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY5MDMzODUyOF5BMl5BanBnXkFtZTcwMTQ3NTMyNA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.1","imdbVotes":"320,993","imdbID":"tt0075148","Type":"movie","Response":"True"},
	{"Title":"The Imitation Game","Year":"2014","Rated":"PG-13","Released":"25 Dec 2014","Runtime":"114 min","Genre":"Biography, Drama, Thriller","Director":"Morten Tyldum","Writer":"Graham Moore, Andrew Hodges (book)","Actors":"Benedict Cumberbatch, Keira Knightley, Matthew Goode, Rory Kinnear","Plot":"Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain's top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.","Language":"English, German","Country":"UK, USA","Awards":"Won 1 Oscar. Another 52 wins & 125 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDkwNTEyMzkzNl5BMl5BanBnXkFtZTgwNTAwNzk3MjE@._V1_SX300.jpg","Metascore":"73","imdbRating":"8.1","imdbVotes":"337,941","imdbID":"tt2084970","Type":"movie","Response":"True"},
  	{"Title":"Pirates of the Caribbean: The Curse of the Black Pearl","Year":"2003","Rated":"PG-13","Released":"09 Jul 2003","Runtime":"143 min","Genre":"Action, Adventure, Fantasy","Director":"Gore Verbinski","Writer":"Ted Elliott (screen story), Terry Rossio (screen story), Stuart Beattie (screen story), Jay Wolpert (screen story), Ted Elliott (screenplay), Terry Rossio (screenplay)","Actors":"Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley","Plot":"This swash-buckling tale follows the quest of Captain Jack Sparrow, a savvy pirate, and Will Turner, a resourceful blacksmith, as they search for Elizabeth Swann. Elizabeth, the daughter of the governor and the love of Will's life, has been kidnapped by the feared Captain Barbossa. Little do they know, but the fierce and clever Barbossa has been cursed. He, along with his large crew, are under an ancient curse, doomed for eternity to neither live, nor die. That is, unless a blood sacrifice is made.","Language":"English","Country":"USA","Awards":"Nominated for 5 Oscars. Another 31 wins & 76 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAyNDM4MTc2N15BMl5BanBnXkFtZTYwNDk0Mjc3._V1_SX300.jpg","Metascore":"63","imdbRating":"8.1","imdbVotes":"726,348","imdbID":"tt0325980","Type":"movie","Response":"True"},
	{"Title":"X-Men: Days of Future Past","Year":"2014","Rated":"PG-13","Released":"23 May 2014","Runtime":"132 min","Genre":"Action, Adventure, Sci-Fi","Director":"Bryan Singer","Writer":"Simon Kinberg (screenplay), Jane Goldman (story), Simon Kinberg (story), Matthew Vaughn (story)","Actors":"Hugh Jackman, James McAvoy, Michael Fassbender, Jennifer Lawrence","Plot":"Sentinels, robots that were created for the purpose of hunting down mutants were released in 1973. 50 years later the Sentinels would also hunt humans who aid mutants. Charles Xavier and his X-Men try their best to deal with the Sentinels but they are able to adapt and deal with all mutant abilities. Charles decides to go back in time and change things. He asks Kitty Pryde who can send a person's consciousness into the person's past to send him but she can only send someone back a few weeks because if she sends someone back further it could harm them. So Logan decides to go back himself because he might be able to withstand it. So Charles tells him that it's Mystique who's responsible because when she learned about the Sentinels she sought out Bolivar Trask the man who created them and killed him. She would be caught and studied and her ability to change was somehow added to the Sentinels which is why they can adapt. Logan must go to the younger Charles and ask him to help; problem is that he was despondent at that time and without his powers because he took a drug which allows him to walk but takes away his powers. Logan is also told to find Magneto.","Language":"English, Vietnamese, French","Country":"USA, UK, Canada","Awards":"Nominated for 1 Oscar. Another 9 wins & 38 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjEwMDk2NzY4MF5BMl5BanBnXkFtZTgwNTY2OTcwMDE@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.1","imdbVotes":"436,254","imdbID":"tt1877832","Type":"movie","Response":"True"},
	{"Title":"Star Wars: Episode V - The Empire Strikes Back","Year":"1980","Rated":"PG","Released":"20 Jun 1980","Runtime":"124 min","Genre":"Action, Adventure, Fantasy","Director":"Irvin Kershner","Writer":"Leigh Brackett (screenplay), Lawrence Kasdan (screenplay), George Lucas (story)","Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams","Plot":"After the Rebel base on the icy planet Hoth is taken over by the empire, Han, Leia, Chewbacca, and C-3PO flee across the galaxy from the Empire. Luke travels to the forgotten planet of Dagobah to receive training from the Jedi master Yoda, while Vader endlessly pursues him.","Language":"English","Country":"USA","Awards":"Won 1 Oscar. Another 15 wins & 17 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjE2MzQwMTgxN15BMl5BanBnXkFtZTcwMDQzNjk2OQ@@._V1_SX300.jpg","Metascore":"79","imdbRating":"8.8","imdbVotes":"709,821","imdbID":"tt0080684","Type":"movie","Response":"True"},
	{"Title":"Star Wars: Episode IV - A New Hope","Year":"1977","Rated":"PG","Released":"25 May 1977","Runtime":"121 min","Genre":"Action, Adventure, Fantasy","Director":"George Lucas","Writer":"George Lucas","Actors":"Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing","Plot":"A young boy from Tatooine sets out on an adventure with an old Jedi named Obi-Wan Kenobi as his mentor to save Princess Leia from the ruthless Darth Vader and Destroy the Death Star built by the Empire which has the power to destroy the entire galaxy.","Language":"English","Country":"USA","Awards":"Won 6 Oscars. Another 38 wins & 27 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTU4NTczODkwM15BMl5BanBnXkFtZTcwMzEyMTIyMw@@._V1_SX300.jpg","Metascore":"92","imdbRating":"8.7","imdbVotes":"773,938","imdbID":"tt0076759","Type":"movie","Response":"True"}]
	


}])

  

















































